// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/__PROTO_FILE__.proto

package __PROTO_PACKAGE__

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	X_GRPC_SERVICE___SayHello_FullMethodName = "/__PROTO_PACKAGE__.__GRPC_SERVICE__/SayHello"
)

// X_GRPC_SERVICE__Client is the client API for X_GRPC_SERVICE__ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type X_GRPC_SERVICE__Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type x_GRPC_SERVICE__Client struct {
	cc grpc.ClientConnInterface
}

func NewX_GRPC_SERVICE__Client(cc grpc.ClientConnInterface) X_GRPC_SERVICE__Client {
	return &x_GRPC_SERVICE__Client{cc}
}

func (c *x_GRPC_SERVICE__Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, X_GRPC_SERVICE___SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// X_GRPC_SERVICE__Server is the server API for X_GRPC_SERVICE__ service.
// All implementations must embed UnimplementedX_GRPC_SERVICE__Server
// for forward compatibility.
type X_GRPC_SERVICE__Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedX_GRPC_SERVICE__Server()
}

// UnimplementedX_GRPC_SERVICE__Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedX_GRPC_SERVICE__Server struct{}

func (UnimplementedX_GRPC_SERVICE__Server) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedX_GRPC_SERVICE__Server) mustEmbedUnimplementedX_GRPC_SERVICE__Server() {}
func (UnimplementedX_GRPC_SERVICE__Server) testEmbeddedByValue()                          {}

// UnsafeX_GRPC_SERVICE__Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to X_GRPC_SERVICE__Server will
// result in compilation errors.
type UnsafeX_GRPC_SERVICE__Server interface {
	mustEmbedUnimplementedX_GRPC_SERVICE__Server()
}

func RegisterX_GRPC_SERVICE__Server(s grpc.ServiceRegistrar, srv X_GRPC_SERVICE__Server) {
	// If the following call panics, it indicates UnimplementedX_GRPC_SERVICE__Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&X_GRPC_SERVICE___ServiceDesc, srv)
}

func _X_GRPC_SERVICE___SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(X_GRPC_SERVICE__Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: X_GRPC_SERVICE___SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(X_GRPC_SERVICE__Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// X_GRPC_SERVICE___ServiceDesc is the grpc.ServiceDesc for X_GRPC_SERVICE__ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var X_GRPC_SERVICE___ServiceDesc = grpc.ServiceDesc{
	ServiceName: "__PROTO_PACKAGE__.__GRPC_SERVICE__",
	HandlerType: (*X_GRPC_SERVICE__Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _X_GRPC_SERVICE___SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/__PROTO_FILE__.proto",
}
