syntax = "proto3";

package usergrouppb;

option go_package = "/usergrouppb;usergrouppb";

service UsergroupService {
  rpc MatchUserGroup (MatchUserGroupRequest) returns (MatchUserGroupResponse);
}

enum ErrorCode {
  ERROR_UNSPECIFIED = 0;
  OK = 1;
  INVALID_PARAM = 2;
  DATA_NOT_EXIST = 3;
  USER_GROUP_NOT_ACTIVE = 4;
  UNKNOWN_ERROR = 100;
}

message BaseResponseInfo {
  ErrorCode code = 1;
  string message = 2;
}

message MatchUserGroupRequest {
  int64 user_id = 1;
  int64 user_group_id = 2;
}

message MatchUserGroupResponse {
  bool matched = 1;
  BaseResponseInfo base_response_info = 255;
}
