// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/usergroup.proto

package usergrouppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsergroupService_MatchUserGroup_FullMethodName = "/usergrouppb.UsergroupService/MatchUserGroup"
)

// UsergroupServiceClient is the client API for UsergroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsergroupServiceClient interface {
	MatchUserGroup(ctx context.Context, in *MatchUserGroupRequest, opts ...grpc.CallOption) (*MatchUserGroupResponse, error)
}

type usergroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsergroupServiceClient(cc grpc.ClientConnInterface) UsergroupServiceClient {
	return &usergroupServiceClient{cc}
}

func (c *usergroupServiceClient) MatchUserGroup(ctx context.Context, in *MatchUserGroupRequest, opts ...grpc.CallOption) (*MatchUserGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchUserGroupResponse)
	err := c.cc.Invoke(ctx, UsergroupService_MatchUserGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsergroupServiceServer is the server API for UsergroupService service.
// All implementations must embed UnimplementedUsergroupServiceServer
// for forward compatibility.
type UsergroupServiceServer interface {
	MatchUserGroup(context.Context, *MatchUserGroupRequest) (*MatchUserGroupResponse, error)
	mustEmbedUnimplementedUsergroupServiceServer()
}

// UnimplementedUsergroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsergroupServiceServer struct{}

func (UnimplementedUsergroupServiceServer) MatchUserGroup(context.Context, *MatchUserGroupRequest) (*MatchUserGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchUserGroup not implemented")
}
func (UnimplementedUsergroupServiceServer) mustEmbedUnimplementedUsergroupServiceServer() {}
func (UnimplementedUsergroupServiceServer) testEmbeddedByValue()                          {}

// UnsafeUsergroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsergroupServiceServer will
// result in compilation errors.
type UnsafeUsergroupServiceServer interface {
	mustEmbedUnimplementedUsergroupServiceServer()
}

func RegisterUsergroupServiceServer(s grpc.ServiceRegistrar, srv UsergroupServiceServer) {
	// If the following call panics, it indicates UnimplementedUsergroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsergroupService_ServiceDesc, srv)
}

func _UsergroupService_MatchUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchUserGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsergroupServiceServer).MatchUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsergroupService_MatchUserGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsergroupServiceServer).MatchUserGroup(ctx, req.(*MatchUserGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsergroupService_ServiceDesc is the grpc.ServiceDesc for UsergroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsergroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usergrouppb.UsergroupService",
	HandlerType: (*UsergroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MatchUserGroup",
			Handler:    _UsergroupService_MatchUserGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usergroup.proto",
}
