// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dao "github.com/nusiss-capstone-project/usergroup-mservice/server/repository/dao"
	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/usergroup-mservice/server/repository/model"
)

// UserGroupDao is an autogenerated mock type for the UserGroupDao type
type UserGroupDao struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, filter
func (_m *UserGroupDao) Count(ctx context.Context, filter dao.UserGroupListFilter) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.UserGroupListFilter) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.UserGroupListFilter) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.UserGroupListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, group
func (_m *UserGroupDao) Create(ctx context.Context, group *model.UserGroup) (int64, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserGroup) (int64, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserGroup) int64); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserGroup) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserGroupDao) GetByID(ctx context.Context, id int64) (*model.UserGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, offset, limit
func (_m *UserGroupDao) List(ctx context.Context, filter dao.UserGroupListFilter, offset int, limit int) ([]*model.UserGroup, error) {
	ret := _m.Called(ctx, filter, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.UserGroupListFilter, int, int) ([]*model.UserGroup, error)); ok {
		return rf(ctx, filter, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.UserGroupListFilter, int, int) []*model.UserGroup); ok {
		r0 = rf(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.UserGroupListFilter, int, int) error); ok {
		r1 = rf(ctx, filter, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, group
func (_m *UserGroupDao) Update(ctx context.Context, group *model.UserGroup) error {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserGroup) error); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *UserGroupDao) UpdateStatus(ctx context.Context, id int64, status string) (*model.UserGroup, error) {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *model.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.UserGroup, error)); ok {
		return rf(ctx, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.UserGroup); ok {
		r0 = rf(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserGroupDao creates a new instance of UserGroupDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserGroupDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserGroupDao {
	mock := &UserGroupDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
